#!/usr/bin/env bash

# Scans and plays TikTok videos with fzf

# Enable strict mode
set -euo pipefail

# Regex
regex=".*\.\(mp4\|mov\|webm\)$"

# Volume
vol="${2:-50}"

# Search for songs in directory and pipe to fzf
# Show thumbnail preview of video and play in mpv
find "$1" -type f -iregex "$regex" \
  | fzf \
    --preview 'ffmpeg -i {} -ss 00:00:00.00 -vframes 1 -f image2 - 2> /dev/null | kitty icat --clear --transfer-mode=memory --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0' \
    --bind "enter:execute:mpv --fs --loop-playlist=inf --volume=$vol {} > /dev/null"
